# services:
#   nginx:
#     build:
#       context: .. # pasta tarefa-1
#       dockerfile: docker/nginx/Dockerfile
#     container_name: nginx_tarefa1
#     ports:
#       - "8001:80"
#       - "4443:443"
#     volumes:
#       - ../nginx_site/html:/usr/share/nginx/html:ro
#       - ../nginx:/etc/nginx/conf.d:ro # << AQUI: monta a pasta inteira
#       - ../pki/server/server.key.pem:/etc/nginx/certs/server.key.pem:ro
#       - ../pki/server/chain.pem:/etc/nginx/certs/chain.pem:ro
#     restart: unless-stopped

version: "3.8"

services:
  nginx:
    build:
      context: .. # raiz da tarefa-1
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_tarefa1
    ports:
      - "8001:80" # HTTP
      - "4443:443" # HTTPS local
    volumes:
      - ../nginx_site/html:/usr/share/nginx/html:ro
      - ../nginx:/etc/nginx/conf.d:ro
      - ../pki/server/server.key.pem:/etc/nginx/certs/server.key.pem:ro
      - ../pki/server/chain.pem:/etc/nginx/certs/chain.pem:ro
    restart: unless-stopped
