version = 5.1.0
archive_dir = /etc/letsencrypt/archive/speaking-representing-technological-sounds.trycloudflare.com
cert = /etc/letsencrypt/live/speaking-representing-technological-sounds.trycloudflare.com/cert.pem
privkey = /etc/letsencrypt/live/speaking-representing-technological-sounds.trycloudflare.com/privkey.pem
chain = /etc/letsencrypt/live/speaking-representing-technological-sounds.trycloudflare.com/chain.pem
fullchain = /etc/letsencrypt/live/speaking-representing-technological-sounds.trycloudflare.com/fullchain.pem
[renewalparams]
account = dd3a7c9213b39737523e1e1ba7df15ba
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
speaking-representing-technological-sounds.trycloudflare.com = /var/www/certbot
